### ISSUE TITLE
Cannot delete uploaded files

### ISSUE THREAD

**Issue by augustincaitlin** [datakind/permanent-colandr-back#14]
If a user uploads the wrong file - cannot delete that uploaded file. Current fix requires a colandr administrator deleting it if emailed. 

Addressing this issue might require code from this repository: https://github.com/datakind/permanent-colandr-front

**Comment by bdewilde** [comment]
looks like a duplicate of https://github.com/datakind/permanent-colandr-back/issues/27 . please reopen if i've misunderstood.
