### ISSUE TITLE
Standard download file does not include everything that users want

### ISSUE THREAD

**Issue by augustincaitlin** [datakind/permanent-colandr-back#33]
Users want things like exclusion reasons at title and abstract and tags and who screened what. Colandr team used to do custom downloads for users but now they can use the Colandr companion to do this. 

To address this issue, might need to use code from this repo: https://github.com/datakind/permanent-colandr-front

**Comment by bdewilde** [comment]
back-end solution merged; requires front-end changes to actually make visible to users
